/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PraktikumOOP;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS ZEPHYRUS
 */
public class PerpustakaanGUI extends javax.swing.JFrame {

    /**
     * Creates new form Perpustakaan
     */
    public PerpustakaanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuDatadiri = new javax.swing.JMenuItem();
        menuKoleksi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuTransaksi = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        menuBuku = new javax.swing.JMenuItem();
        menuDisk = new javax.swing.JMenuItem();
        menuMajalah = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan PBO Praktikum 2");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Peminjam", "Nama", "Pekerjaan", "Nomor ID", "Tipe Koleksi"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuDatadiri.setText("Peminjam ");
        menuDatadiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDatadiriActionPerformed(evt);
            }
        });
        jMenu2.add(menuDatadiri);

        menuKoleksi.setText("Koleksi");
        menuKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKoleksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuKoleksi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuTransaksi.setText("Pinjam");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        jMenu3.add(menuTransaksi);

        exit.setText("Kembali");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Tampil");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu10.setText("Koleksi");

        menuBuku.setText("Buku");
        menuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBukuActionPerformed(evt);
            }
        });
        jMenu10.add(menuBuku);

        menuDisk.setText("Disk");
        menuDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiskActionPerformed(evt);
            }
        });
        jMenu10.add(menuDisk);

        menuMajalah.setText("Majalah");
        menuMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMajalahActionPerformed(evt);
            }
        });
        jMenu10.add(menuMajalah);

        jMenu6.add(jMenu10);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Help");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void menuKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKoleksiActionPerformed
        Koleksi koleksi = new Koleksi();
        KoleksiGUI koleksiGui = new KoleksiGUI(this, true);
        koleksiGui.setVisible(true);
        
    }//GEN-LAST:event_menuKoleksiActionPerformed

    private void menuDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiskActionPerformed
        DiskGUI disk = new DiskGUI(this, true);
        disk.setVisible(true);
    }//GEN-LAST:event_menuDiskActionPerformed

    private void menuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBukuActionPerformed
        BukuGUI buku = new BukuGUI(this, true);
        buku.setVisible(true);
    }//GEN-LAST:event_menuBukuActionPerformed

    private void menuDatadiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDatadiriActionPerformed
        PeminjamGUI dataDiri = new PeminjamGUI(this, true);
        dataDiri.setVisible(true);
    }//GEN-LAST:event_menuDatadiriActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        TransaksiGUI transaksi = new TransaksiGUI(this, true);
        transaksi.setVisible(true);
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMajalahActionPerformed
        MajalahGUI mjlh = new MajalahGUI(this, true);
        mjlh.setVisible(true);
    }//GEN-LAST:event_menuMajalahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerpustakaanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerpustakaanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerpustakaanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerpustakaanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerpustakaanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuBuku;
    private javax.swing.JMenuItem menuDatadiri;
    private javax.swing.JMenuItem menuDisk;
    private javax.swing.JMenuItem menuKoleksi;
    private javax.swing.JMenuItem menuMajalah;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
