/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jasa_pencarian_kos;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;
import static java.time.LocalDate.now;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author yayuchristy
 */
public class InsertData extends javax.swing.JFrame {

    Koneksi kon;
    Connection conn;
    LocalDate waktu = LocalDate.now();

    /**
     * Creates new form InsertData
     */
    public InsertData() {
        initComponents();
        kon = new Koneksi();
        this.setLocationRelativeTo(null);
    }

    public void inputData() throws SQLException, IOException {
        conn = null;
        PreparedStatement ps = null;
        conn = kon.getConnection();
        String nama = jTextFieldNama.getText();
        String tipeKamar = (String) jComboBoxTipeKamar.getSelectedItem();
        String statusBayar = "BELUM";
        String tagihan = "";

        if (tipeKamar.equals("Tipe A")) {
            tagihan = "2000000";
        } else if (tipeKamar.equals("Tipe B")) {
            tagihan = "1500000";
        } else if (tipeKamar.equals("Tipe C")) {
            tagihan = "1000000";
        } else {
            JOptionPane.showMessageDialog(null, "Harap pilih tipe kamar terlebih dahulu !");
        }
        if (jRadioButtonStatusBelum.isSelected() == false) {
            statusBayar = "SUDAH";
        }
        String statusKamar = "TERISI";
        if (statusBayar == "SUDAH") {
        }
        try {
            ps = conn.prepareStatement("Insert into penghuni values(DEPT_SE.NEXTVAL,UPPER(?),?,?,?,?,?)");
            ps.setString(1, nama);
            ps.setString(2, tipeKamar);
            ps.setString(3, tagihan);
            ps.setString(4, statusKamar);
            ps.setString(5, statusBayar);
            if (statusBayar == "BELUM") {
                ps.setDate(6, null);
            } else {
                ps.setDate(6, Date.valueOf(waktu));

            }
            ps.executeUpdate();
            conn.commit();
            JOptionPane.showMessageDialog(null, "Data sudah ditambahkan!");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                ps.close();
                conn.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
}
    }

    public void tulis() throws IOException, SQLException {
        conn = kon.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(" SELECT * FROM PENGHUNI ");
        FileWriter fileWriter = new FileWriter("Data Pembayaran.txt");
        fileWriter.write("DATA PEMBAYARAN BULAN " + waktu.getMonth());
        fileWriter.write("\n===============================================================");
        fileWriter.write("\nNAMA\t\tTIPE KAMAR\tTAGIHAN\t\tTANGGAL BAYAR ");
        fileWriter.write("\n===============================================================");
        while (rs.next()) {
            try {
                Date tam = rs.getDate(7);
                if (tam == null) {
                    fileWriter.write("\n" + rs.getString(2) + "\t\t" + rs.getString(3) + "\t\t" + rs.getString(4) + "\t\tBELUM BAYAR");
                } else {
                    fileWriter.write("\n" + rs.getString(2) + "\t\t" + rs.getString(3) + "\t\t" + rs.getString(4) + "\t\t" + rs.getDate(7));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        fileWriter.close();
        rs.close();
        st.close();
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxTipeKamar = new javax.swing.JComboBox<>();
        jRadioButtonStatusSudah = new javax.swing.JRadioButton();
        jRadioButtonStatusBelum = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input Data");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 14)); // NOI18N
        jLabel1.setText("Masukan Data ");

        jLabel2.setText("Nama :");

        jLabel3.setText("Tipe Kamar  :");

        jLabel4.setText("Status bayar  : ");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxTipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe", "Tipe A", "Tipe B", "Tipe C" }));
        jComboBoxTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipeKamarActionPerformed(evt);
            }
        });

        jRadioButtonStatusSudah.setText("Sudah");
        jRadioButtonStatusSudah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusSudahActionPerformed(evt);
            }
        });

        jRadioButtonStatusBelum.setText("Belum");
        jRadioButtonStatusBelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusBelumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNama)
                        .addComponent(jComboBoxTipeKamar, 0, 282, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonStatusSudah)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButtonStatusBelum)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonStatusSudah)
                    .addComponent(jRadioButtonStatusBelum))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        new Pemilik_Kos().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipeKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipeKamarActionPerformed

    private void jRadioButtonStatusSudahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusSudahActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonStatusSudah.isSelected() == true) {
            jRadioButtonStatusBelum.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonStatusSudahActionPerformed

    private void jRadioButtonStatusBelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusBelumActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonStatusBelum.isSelected() == true) {
            jRadioButtonStatusSudah.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonStatusBelumActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            // TODO add your handling code here:
            if (jTextFieldNama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
                jTextFieldNama.requestFocus();;
            } else {
                if (jComboBoxTipeKamar.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Silahkan pilih tipe kamar !");
                } else {
                    if (jRadioButtonStatusSudah.isSelected() == false && jRadioButtonStatusBelum.isSelected() == false) {
                        JOptionPane.showMessageDialog(null, "Silahkan pilih status bayar!");
                    } else {
                        inputData();
                        tulis();
                        jTextFieldNama.setText("");
                        jComboBoxTipeKamar.setSelectedIndex(0);
                        jRadioButtonStatusBelum.setSelected(false);
                        jRadioButtonStatusSudah.setSelected(false);
                    }
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(InsertData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InsertData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxTipeKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonStatusBelum;
    private javax.swing.JRadioButton jRadioButtonStatusSudah;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
