/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jasa_pencarian_kos;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yayuchristy
 */
public class Pemilik_Kos extends javax.swing.JFrame {

    Connection conn = null;
    Statement st = null;
    PreparedStatement ps = null;
    LocalDate now = LocalDate.now();
    Koneksi kon;

    /**
     * Creates new form Pemilik_Kos1
     */
    public Pemilik_Kos() {
        initComponents();
        this.setLocationRelativeTo(null);
        kon = new Koneksi();
        conn = kon.getConnection();
        String bulan = now.getMonth().toString();
        jLabelpesan1.setText("Sudahkan Anda mengupdate data pembayaran bulan " + bulan.toLowerCase() + " ?");
    }

    public void ubahstatuspembayaran() throws IOException {
        try {
            ps = conn.prepareStatement("UPDATE PENGHUNI set Status_bayar=UPPER(?), tanggal_bayar = ? ");
            ps.setString(1, "BELUM");
            ps.setDate(2, null);
            ps.executeUpdate();
            conn.commit();
            JOptionPane.showMessageDialog(null, "Status Pembayaran telah di update");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void tulis() throws IOException, SQLException {
        conn = kon.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(" SELECT * FROM PENGHUNI");
        FileWriter fileWriter = new FileWriter("Data Pembayaran.txt");
        fileWriter.write("DATA PEMBAYARAN BULAN " + now.getMonth());
        fileWriter.write("\n===============================================================");
        fileWriter.write("\nNAMA\t\tTIPE KAMAR\tTAGIHAN\t\tTANGGAL BAYAR ");
        fileWriter.write("\n===============================================================");
        while (rs.next()) {
            try {
                Date tam = rs.getDate(7);
                if (tam == null) {
                    fileWriter.write("\n" + rs.getString(2) + "\t\t" + rs.getString(3) + "\t\t" + rs.getString(4) + "\t\tBELUM BAYAR");
                } else {
                    fileWriter.write("\n" + rs.getString(2) + "\t\t" + rs.getString(3) + "\t\t" + rs.getString(4) + "\t\t" + rs.getDate(7));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        fileWriter.close();
        rs.close();
        st.close();
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelpesan = new javax.swing.JLabel();
        jButtonbelum = new javax.swing.JButton();
        jButtonsudah = new javax.swing.JButton();
        jLabelpesan1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLihatData = new javax.swing.JMenuItem();
        jMenuIteminputData = new javax.swing.JMenuItem();
        jMenuItemUpdateData = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemilik Kos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jasa_pencarian_kos/TERANG fix.png"))); // NOI18N

        jButtonbelum.setText("BELUM");
        jButtonbelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbelumActionPerformed(evt);
            }
        });

        jButtonsudah.setText("SUDAH");
        jButtonsudah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsudahActionPerformed(evt);
            }
        });

        jLabelpesan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelpesan1.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabelpesan))
                    .addComponent(jLabelpesan1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonsudah)
                .addGap(71, 71, 71)
                .addComponent(jButtonbelum)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelpesan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonbelum)
                    .addComponent(jButtonsudah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));

        jMenu1.setBackground(new java.awt.Color(0, 102, 102));
        jMenu1.setText("Penghuni");

        jMenuItemLihatData.setText("Lihat Data Penghuni");
        jMenuItemLihatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLihatDataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLihatData);

        jMenuIteminputData.setText("Input Data Penghuni");
        jMenuIteminputData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteminputDataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIteminputData);

        jMenuItemUpdateData.setText("Update Data Penghuni");
        jMenuItemUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateDataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUpdateData);
        jMenu1.add(jSeparator2);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLihatDataActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new ShowData().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemLihatDataActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        new Halaman_Utama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuIteminputDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteminputDataActionPerformed
        // TODO add your handling code here:
        new InsertData().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuIteminputDataActionPerformed

    private void jMenuItemUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateDataActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new UpdateData().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemUpdateDataActionPerformed

    private void jButtonbelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbelumActionPerformed
        if (JOptionPane.showConfirmDialog(null, "yakin ingin mengubah status pembayaran ?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                ubahstatuspembayaran();
                tulis();
            } catch (IOException ex) {
                Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Pemilik_Kos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Baik. Terima kasih :)");
        }

    }//GEN-LAST:event_jButtonbelumActionPerformed

    private void jButtonsudahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsudahActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Baik. Terima kasih :)");
    }//GEN-LAST:event_jButtonsudahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilik_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilik_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilik_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilik_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilik_Kos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbelum;
    private javax.swing.JButton jButtonsudah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelpesan;
    private javax.swing.JLabel jLabelpesan1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLihatData;
    private javax.swing.JMenuItem jMenuItemUpdateData;
    private javax.swing.JMenuItem jMenuIteminputData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
