/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jasa_pencarian_kos;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author yayuchristy
 */
public class ShowData extends javax.swing.JFrame {

    Koneksi kon;
    Connection conn;

    /**
     * Creates new form ShowData
     */
    public ShowData() throws SQLException {
        initComponents();
        kon = new Koneksi();
        conn = kon.getConnection();
        Tampil();
    }

    public void lebarKolom() {
        //sumber : https://top-ilmu.blogspot.com/2013/07/cara-mengatur-lebar-kolom-tabel-netbeans.html
        TableColumn column;
        jTablePenghuni.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTablePenghuni.getColumnModel().getColumn(0);
        column.setPreferredWidth(50);
        column = jTablePenghuni.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = jTablePenghuni.getColumnModel().getColumn(2);
        column.setPreferredWidth(80);
        column = jTablePenghuni.getColumnModel().getColumn(3);
        column.setPreferredWidth(80);
        column = jTablePenghuni.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
        column = jTablePenghuni.getColumnModel().getColumn(5);
        column.setPreferredWidth(80);
        column = jTablePenghuni.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
    }

    public void Tampil() throws SQLException {
        String queryStr = "SELECT * FROM PENGHUNI ORDER BY ID_PENGHUNI";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(queryStr);
        ArrayList id = new ArrayList();
        ArrayList nama = new ArrayList();
        ArrayList tipeKamar = new ArrayList();
        ArrayList tagihan = new ArrayList();
        ArrayList statusKamar = new ArrayList();
        ArrayList statusBayar = new ArrayList();
        ArrayList tglBayar = new ArrayList();

        lebarKolom();
        int count = 0;
        while (rs.next()) {
            id.add(rs.getString("id_penghuni"));
            nama.add(rs.getString("nama"));
            tipeKamar.add(rs.getString("tipe_kamar"));
            tagihan.add(rs.getString("tagihan_perbulan"));
            statusKamar.add(rs.getString("status_kamar"));
            statusBayar.add(rs.getString("status_bayar"));
            tglBayar.add(rs.getString("tanggal_bayar"));

            DefaultTableModel model = (DefaultTableModel) jTablePenghuni.getModel();
            model.addRow(new Object[]{id.get(count), nama.get(count), tipeKamar.get(count), tagihan.get(count), statusKamar.get(count), statusBayar.get(count), tglBayar.get(count)});
            count++;
        }
        rs.close();
        stmt.close();
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePenghuni = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show Data");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DATA PENGHUNI");

        jTablePenghuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Tipe Kamar", "Tagihan/bln", "Status Kamar", "Status Bayar", "Tgl Bayar"
            }
        ));
        jScrollPane1.setViewportView(jTablePenghuni);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButtonOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOK)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        new Pemilik_Kos().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowData().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowData.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePenghuni;
    // End of variables declaration//GEN-END:variables
}
